.TH INTERNSCTL 1 "Your Date" "0.1.0" "Internsctl User Manuals"
.SH NAME
internsctl \- a custom command for operational tasks.
.SH SYNOPSIS
.B internsctl
[\fIOPTION\fR]
.SH DESCRIPTION
\fBinternsctl\fR is a custom script designed to perform operational tasks.
.SH OPTIONS
.TP
\fB\-\-help\fR
Display the help message and exit.

.TP
\fB\-\-version\fR
Output version information and exit.
.SH EXAMPLES
.TP
.B internsctl --help
Displays the help dialogue.

.TP
.B internsctl --version
Displays the script version.
.SH AUTHOR
Written by [Aakash].
